### ISSUE TITLE
question about IIBGNN

### ISSUE THREAD

**Issue by chengjackjelly** [christam96/Blockchain-GNN-Research#19]
I am currently working on reproducing the code from this paper. I am wondering if you know the explicit way of calculating the subgraph in this paper. 
![image](https://user-images.githubusercontent.com/76078595/165530202-4f1bf5a9-1d89-4d04-83ab-c14b7e2c8b1f.png)

The paper has mentioned that the subgraph is calculated by EACH account  in nA with adding it's direct neighbor. But the picture it shows later turns out that it evolved the neighbor's neighbor of the account in nA. 
And it also mentions a number "nu" which refers the up-limit of nodes. so when we train the network, is this number fixed or not?

**Comment by christam96** [comment]
@chengjackjelly

> The paper has mentioned that the subgraph is calculated by EACH account in nA with adding it's direct neighbor. But the picture it shows later turns out that it evolved the neighbor's neighbor of the account in nA.

I believe this section describes subgraph extraction for `1st-order` and `2nd-order` subgraphs. In `1st-order` subgraphs only the immediate neighbours are added to the subgraph. In `2nd-order` subgraphs additional nodes are added from the k-hop neighbourhood with k=2, meaning each neighbor's neighbor will also be added. In both cases, the maximum number of nodes added to the subgraph is _n_u_ (in which case the top _n_u_ transaction volume neighbors are selected). 

> And it also mentions a number "nu" which refers the up-limit of nodes. so when we train the network, is this number fixed or not?

Yes, I believe _n_u_ is fixed during training. Perhaps it can be used as a sort of hyperparameter though.
